name: Generate DSA Java Code

on:
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC (1st run)
    - cron: "0 3 * * *"   # 03:00 UTC (2nd run)
    - cron: "0 6 * * *"   # 06:00 UTC (3rd run)
    - cron: "0 9 * * *"   # 09:00 UTC (4th run)
    - cron: "0 12 * * *"  # 12:00 UTC (5th run)
    - cron: "0 15 * * *"  # 15:00 UTC (6th run)
    - cron: "0 18 * * *"  # 18:00 UTC (7th run)
    - cron: "0 20 * * *"  # 20:00 UTC (8th run)
    - cron: "0 22 * * *"  # 22:00 UTC (9th run)
    - cron: "0 23 * * *"  # 23:00 UTC (10th run)
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # Grants write access for push

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai

      - name: Generate DSA Code
        env:
          GOOGLE_API_KEY: ${{ secrets.API_KEY }}  # Updated to match script expectation
        run: python generate_dsa.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add *.java generated_problems.txt
          git commit -m "Add new DSA Java code" || echo "No changes to commit"
          git push
